# Base on https://github.com/sarbagyastha/youtube_player_flutter/blob/master/.travis.yml
matrix:
  # This causes the build to complete immediately upon first failure or once required jobs are green.
  fast_finish: true

  # Not waiting for APK build to finish.
  allow_failures:
  - env: JOB=APK
  - env: JOB=IPA

  include:
    - env: JOB=PR
      os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - lib32stdc++6
            #- fonts-droid

      before_script:
        - git clone --branch v1.9.1+hotfix.4 https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH

      script:
        - flutter doctor -v
        - flutter test --coverage --coverage-path=lcov.info

    # Building an APK.
    - env: JOB=APK
      os: linux
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-29.0.2
          - android-29
          - sys-img-armeabi-v7a-google_apis-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - lib32stdc++6
            #- fonts-droid
      before_install:
        - yes | sdkmanager --update # key row
      before_script:
        - wget http://services.gradle.org/distributions/gradle-5.3.1-bin.zip
        - unzip -qq gradle-5.3.1-bin.zip
        - export GRADLE_HOME=$PWD/gradle-5.3.1
        - export PATH=$GRADLE_HOME/bin:$PATH
        - git clone --branch v1.9.1+hotfix.4 https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - yes | flutter doctor --android-licenses # key row

      script:
        - flutter -v build apk

    # Building an IPA.
    - env: JOB=IPA
      os: osx
      language: generic
      osx_image: xcode11.3
      before_script:
        - pip3 install six
        - brew update
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone --branch v1.9.1+hotfix.4 https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - sudo gem uninstall cocoapods
        - sudo gem install cocoapods -v 1.7.5
        - pod setup
        - pod --version
        - flutter doctor -v

      script:
        - flutter build ios --no-codesign
